#!/bin/bash

DEFAULT_USERNAME="marcelo"
USERNAME="madias-m42"
HOSTNAME="madias-m42"

#__Before the script execution, the mannually execution of the commands bellow is a must__
# su root
# apt install sudo
# sudo groupadd user42
# sudo usermod -aG sudo $USER_NAME
# sudo usermod -aG user42 $USER_NAME
# exit
#__END__

# Configure sudo
echo "Configuring Sudo rules"
sudo mkdir /var/log/sudo
echo 'Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin”' | sudo EDITOR='tee -a' visudo
echo 'Defaults    passwd_tries = 3' | sudo EDITOR='tee -a' visudo
echo 'Defaults    badpass_message = "Wrong Password!"' | sudo EDITOR='tee -a' visudo
echo 'Defaults    logfile = "/var/log/sudo/sudo.log"' | sudo EDITOR='tee -a' visudo
echo 'Defaults    log_input, log_output' | sudo EDITOR='tee -a' visudo
echo 'Defaults    iolog_dir = "/var/log/sudo"' | sudo EDITOR='tee -a' visudo
echo 'Defaults    requiretty' | sudo EDITOR='tee -a' visudo


# Configure SSH
echo "Configuring SSH server"
sudo apt -y install openssh-server
sudo cat >> /etc/ssh/sshd_config << EOF
Port 4242
PermitRootLogin no
PasswordAuthentication yes
EOF

#Configure Firewall (UFW)
echo "Configuring UFW"
sudo apt -y install ufw
sudo ufw enable
sudo ufw allow 4242

#Configure User and Password Quality
echo "Configuring user and passwdor quality..."
sed -i 's/PASS_MAX_DAYS 99999/PASS_MAX_DAYS 30/g' /etc/login.defs
sed -i 's/PASS_MIN_DAYS 0/PASS_MAX_DAYS 30/g' /etc/login.defs
sed -i 's/PASS_WARN_AGE 7/PASS_MAX_DAYS 30/g' /etc/login.defs
chage --mindays 2 --maxdays 30 --warndays 7 $DEFAULT_USERNAME
chage --mindays 2 --maxdays 30 --warndays 7 root
if ! grep $USERNAME /etc/passwd; then
	sudo useradd -m $USERNAME
fi

if ! grep sudo /etc/group | grep $USERNAME; then
	sudo usermod -aG sudo $USERNAME
fi

if ! grep user42 /etc/group | grep $USERNAME; then
	sudo usermod -aG user42 $USERNAME
fi
chsh -s /bin/bash/ $USERNAME
sudo apt -y install libpam-pwquality
sudo sed -i 's/password	requisite			pam_pwquality.so retry=3/password	requisite		pam_pwquality.so retry=3 minlen=10 ucredit=-1 dcredit=-1 lcredit=-1 maxrepeat=3 reject_username difok=7 enforce_for_root/g' /etc/pam.d/common-password

#Change Hostname
echo "Changing Hostname..."
hostnamectl set-hostname $HOSTNAME
sed -i "s/127.0.1.1	debian/127.0.1.1	$HOSTNAME/g" /etc/hosts

#_____After the Script execution, don't forget to run the fallowing commands:___
#ssh-keygen -t rsa



