# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: madias-m <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/10 13:32:31 by madias-m          #+#    #+#              #
#    Updated: 2023/10/10 13:59:13 by madias-m         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FLAGS = -Wall -Wextra -Werror

all:	$(NAME)

$(NAME):
	gcc $(FLAGS) main.c -o $(NAME)

clean:
	ls

fclean: clean
	rm -f $(NAME)
